# Generated by Django 3.2.4 on 2021-08-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Movie', 'Movie'), ('Show', 'Show'), ('Webseries', 'Webseries'), ('Kids', 'Kids')], max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('discription', models.CharField(blank=True, max_length=10000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('language', models.CharField(choices=[('Telugu', 'Telugu'), ('Hindi', 'Hindi'), ('Tamil', 'Tamil'), ('Malayalam', 'Malayalam'), ('Kannada', 'Kannada'), ('English', 'English')], max_length=500)),
                ('geners', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Horror', 'Horror'), ('Thirller', 'Thirller'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Sci Fi', 'Sci Fi')], max_length=500)),
                ('screen_shot', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('movie_length', models.CharField(blank=True, max_length=50, null=True)),
                ('movie_director', models.CharField(blank=True, max_length=200, null=True)),
                ('actor_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('movie_link', models.CharField(blank=True, max_length=10000, null=True)),
                ('status', models.BooleanField(default=0)),
            ],
        ),
    ]
