# Generated by Django 3.2.4 on 2021-08-10 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieshd', '0002_customer_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='company_name',
        ),
    ]
