# Generated by Django 3.2.4 on 2021-08-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieshd', '0003_remove_publisher_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
