# Generated by Django 3.2.4 on 2021-08-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieshd', '0004_publisher_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_categories',
            name='uploader_name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
