# Generated by Django 3.2.4 on 2021-08-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieshd', '0005_add_categories_uploader_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_amount', models.IntegerField(max_length=500)),
                ('payment_order_id', models.IntegerField(max_length=500)),
            ],
        ),
    ]
