# Generated by Django 3.2.4 on 2021-08-16 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieshd', '0009_membership_payhistory_subscription_usermembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='user_membership',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='movieshd.usermembership'),
        ),
        migrations.DeleteModel(
            name='PayHistory',
        ),
    ]
