# Generated by Django 3.2.4 on 2021-08-16 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movieshd', '0010_auto_20210816_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermembership',
            name='order_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
